I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 292, in script
    show charon bg
Exception: Image 'charon' does not accept attributes 'bg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 292, in script
    show charon bg
  File "C:\Users\hhall\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\hhall\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Users\hhall\Downloads\renpy-8.2.3-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\hhall\Downloads\renpy-8.2.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\hhall\Downloads\renpy-8.2.3-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "C:\Users\hhall\Downloads\renpy-8.2.3-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'charon' does not accept attributes 'bg'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
Dana Game 1.0
Mon Dec  2 17:00:46 2024
